INSERT INTO location(name, lat, lon) VALUES('gymkhana', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hospital', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel10', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('central library', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel12', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel14', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel13', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel6', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel7', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel9', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel18', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel4', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel5', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel3', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel2', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel1', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('devi temple', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('lakeside road', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('main gate', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('convocation hall', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('tennis court', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('kendriya vidyalaya', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('main building', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('infinity corridoor', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('aerospace department', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('mech', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('csre building', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('vidya nivas', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('campus school', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('white house', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('sameer hill', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel15', '0.0', '0.0');
INSERT INTO location(name, lat, lon) VALUES('hostel16', '0.0', '0.0');
